- name: Ensure jenkins directory on docker host
  file:
    state: directory
    owner: 1000
    group: 1000
    path: /share/jenkins

- name: Pull Jenkins image
  community.docker.docker_image:
    name: jenkins/jenkins:lts
    source: pull
    pull:
      platform: amd64

- name: Create a container from the jenkins docker image
  community.docker.docker_container:
    name: "jenkins-server"
    image: "jenkins/jenkins:lts"
    expose:
        - 8080
        - 50000
    ports:
        - 0.0.0.0:8080:8080
        - 0.0.0.0:50000:50000
    volumes:
        - "/share/jenkins:/var/jenkins_home"
        - "/var/run/docker.sock:/var/run/docker.sock"
    state: present
    recreate: no

- name: Copy systemd service script to start and stop the jenkins container
  copy: src=files/jenkins.service dest=/etc/systemd/system

- name: Reload systemctl
  shell: systemctl reload-or-restart jenkins

- name: Enable the jenkins service
  shell: systemctl enable jenkins
