- name: Create elastic search volume
  docker_volume:
    name: esdata
    driver: local

- name: Create a network
  docker_network:
    name: "{{ network_name }}"

- name: Start elastic search container
  docker_container:
    name: "{{ elasticsearch_hostname }}"
    image: "{{ elasticsearch_image }}"
    env:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: "true"
      xpack.monitoring.collection.enabled: "true"
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
    ulimits:
      - nofile:65535:65535
    networks:
      - name: "{{ network_name }}"
    state: started
    expose:
      - 9200
    ports:
      - 0.0.0.0:9200:9200
    log_driver: "{{ log_driver }}"
    log_options:
      max-size: "{{ log_max_size }}"
      max-file: "{{ log_max_file }}"
      
# - name: Update password via ES API
#   uri:
#     url: http://{{ elasticsearch_hostname }}:9200/_xpack/security/user/{{elastic_username}}/_password
#     method: POST
#     body_format: json
#     body: "{ \"password\":\"{{ elastic_new_password }}\" }"
#     status_code: 200
#     user: "{{elastic_username}}"
#     password: "{{elastic_password}}"
#     force_basic_auth: yes

- debug:
    msg: >
      Users have to be configured manually. Enable and set the password for the default users with:
      `docker exec -it {{ elasticsearch_hostname }} /bin/bash -c "elasticsearch-setup-passwords auto"`
      Then edit the `vaul.yml` file and copy the password values to the expected variable.
