pipeline {
    agent { 
        dockerfile {
            filename './Task4/docker/extra/Dockerfile'
            args  '-v /tmp:/tmp -u root:sudo -v /var/run/docker.sock:/var/run/docker.sock -v $(which docker):/usr/bin/docker'
        } 
    }
    environment {
        PASSWORD = credentials('JENKINS-SECRET-TEXT')
    }
    stages {
        stage('Check running containers') {
            steps {
                sh 'sudo docker run -p 5000:5000 --name flask-app -d flask-app'
            }
        }
        stage('Docker ps') {
            steps {
                 sh 'sudo docker ps -a'
            }
        }
    }
}