pipeline {
    agent { 
        dockerfile {
            filename './Task4/docker/extra/Dockerfile'
            args '-u root:sudo'
            label ''
        } 
    }
    environment {
        PASSWORD = credentials('JENKINS-SECRET-TEXT')
    }
    stages {
        stage('Test hyp') {
            steps {
                sh 'mkdir this_dir_in_jmaster_server'
                sh 'hostname'
                sh 'pwd'
            }
        }
    }
}