version: "3"

services:
    extra-app:
        image: elbrus/exadel_practices
        scale: 5
        ports:
            - "5000"
    tomcat:
        container_name: tomcat
        image: tomcat
        ports:
            - "8888:8080"
    db:
        image: postgres
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        env_file:
            - .env
    nginx:
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - extra-app
        ports:
            - "4000:4000"