pipeline {
    agent { 
        dockerfile {
            filename './Task4/docker/extra/Dockerfile'
            args '-u root:sudo'
        } 
    }
    environment {
        PASSWORD = credentials('JENKINS-SECRET-TEXT')
    }
    stages {
        stage('Update repo list') {
            steps {
                sh 'apt update -y'
            }
        }
        stage('Test') {
            steps {
                sh 'python3 --version'
                sh 'echo ${PASSWORD}'
            }
        }
    }
}